BASE_DIR="$HOME/dev"
CONFIG_DIR="~/.config"

TOOLS_DIR="$BASE_DIR/tools"
TOOLS_INSTALL_DIR="$TOOLS_DIR/install"

SOFTWARE_DIR="$BASE_DIR/software"
SOFTWARE_INSTALL_DIR="$SOFTWARE_DIR/install"

LSP_DIR="$BASE_DIR/lsp"
LSP_INSTALL_DIR="$LSP_DIR/install"

FORMATTER_DIR="$BASE_DIR/formatter"
FORMATTER_INSTALL_DIR="$FORMATTER_DIR/install"
